#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""
Apply keys/otp_device_secrets.json into TF-M flash-emulated OTP provision data.

Writes otp_device_secrets.inc fragments included by otp_provision.c:
  - HUK / IAK (early fields)
  - boot_seed / implementation_id (later fields)

Workflow:
  1) cp keys/otp_device_secrets.example.json keys/otp_device_secrets.json
  2) edit huk / iak / boot_seed / implementation_id (64 hex chars = 32 bytes)
  3) ./buildtfm.sh test
  4) ./flash_stm32h573.sh  or  ./flash_stm32h5f4.sh
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

FIELDS = ("huk", "iak", "boot_seed", "implementation_id")


def parse_hex32(name: str, value: str) -> bytes:
    s = "".join(value.split())
    if s.lower().startswith("0x"):
        s = s[2:]
    if len(s) != 64:
        raise ValueError(f"{name}: need 32 bytes (64 hex chars), got {len(s)} hex chars")
    try:
        raw = bytes.fromhex(s)
    except ValueError as exc:
        raise ValueError(f"{name}: invalid hex") from exc
    if len(raw) != 32:
        raise ValueError(f"{name}: need 32 bytes")
    return raw


def c_array(data: bytes, indent: str = "        ") -> str:
    parts = [f"0x{b:02X}" for b in data]
    lines = []
    for i in range(0, 32, 8):
        lines.append(indent + ", ".join(parts[i : i + 8]) + ",")
    return "\n".join(lines)


def write_if_changed(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_file() and path.read_text(encoding="utf-8") == text:
        print(f">>> unchanged {path}")
        return
    path.write_text(text, encoding="utf-8")
    print(f">>> updated {path}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo-root", required=True, type=Path)
    ap.add_argument("--json", type=Path, default=None)
    ap.add_argument("--example", type=Path, default=None)
    args = ap.parse_args()

    root: Path = args.repo_root.resolve()
    json_path = (args.json or (root / "keys" / "otp_device_secrets.json")).resolve()
    example = (args.example or (root / "keys" / "otp_device_secrets.example.json")).resolve()
    prov = (
        root
        / "trusted-firmware-m"
        / "platform"
        / "ext"
        / "target"
        / "stm"
        / "common"
        / "hal"
        / "provision"
    )

    if not json_path.is_file():
        if not example.is_file():
            print(f"错误: 缺少 {json_path} 且没有示例 {example}", file=sys.stderr)
            return 1
        json_path.parent.mkdir(parents=True, exist_ok=True)
        json_path.write_text(example.read_text(encoding="utf-8"), encoding="utf-8")
        print(f">>> 已从示例创建 {json_path}")
        print("    请按需修改 huk/iak 后重新编译；当前使用示例值。")

    data = json.loads(json_path.read_text(encoding="utf-8"))
    parsed = {name: parse_hex32(name, data[name]) for name in FIELDS}

    if int.from_bytes(parsed["iak"][:8], "little") == 0xA4906F6DB254B4A9:
        print(
            "错误: IAK 仍是 TF-M dummy 前缀。TFM_DUMMY_PROVISIONING=OFF 时请换成自己的密钥。",
            file=sys.stderr,
        )
        return 1

    huk_iak = "\n".join(
        [
            "/* Auto-generated by scripts/apply_stm_otp_device_secrets.py — do not edit. */",
            f"/* Source: {json_path.name} */",
            "    .huk = {",
            c_array(parsed["huk"]),
            "    },",
            "    .iak = {",
            c_array(parsed["iak"]),
            "    },",
            "",
        ]
    )
    seed_impl = "\n".join(
        [
            "/* Auto-generated by scripts/apply_stm_otp_device_secrets.py — do not edit. */",
            f"/* Source: {json_path.name} */",
            "    .boot_seed = {",
            c_array(parsed["boot_seed"]),
            "    },",
            "    .implementation_id = {",
            c_array(parsed["implementation_id"]),
            "    },",
            "",
        ]
    )
    write_if_changed(prov / "otp_device_secrets.inc", huk_iak)
    write_if_changed(prov / "otp_device_seed_impl.inc", seed_impl)

    meta = root / "keys" / "otp_flash_emulated.addr.txt"
    meta.write_text(
        "Flash-emulated OTP (HUK/IAK/…) is at 0x0C028000\n"
        "Programmed via bl2.hex (.BL2_OTP) and/or explicit OTP hex in flash scripts.\n"
        f"Secrets source: {json_path}\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
