#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""
Sync STM flash-OTP ROTPK hashes from MCUboot signing private keys.

Updates:
  - platform/.../hal/provision/otp_rotpk_hashes.inc  (included by otp_provision.c)
  - bl2/src/provisioning.c  ASSEMBLY_AND_TEST_PROV_DATA_KIND_{0,1} (matching algo)

Hash rules (match TF-M dummy provisioning):
  EC-P256/P384: SHA-256/384 of SubjectPublicKeyInfo DER
  RSA-2048/3072: SHA-256 of PKCS#1 public key DER
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

try:
    from cryptography.hazmat.backends import default_backend
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import ec, rsa
except ImportError as exc:  # pragma: no cover
    print("错误: 需要 cryptography（./buildtfm.sh 的 .venv 里一般已有）", file=sys.stderr)
    raise SystemExit(2) from exc


def load_private_key(path: Path):
    data = path.read_bytes()
    return serialization.load_pem_private_key(data, password=None, backend=default_backend())


def pubkey_hash_bytes(priv, sig_type: str) -> bytes:
    pub = priv.public_key()
    if sig_type.startswith("EC-P"):
        der = pub.public_bytes(
            serialization.Encoding.DER,
            serialization.PublicFormat.SubjectPublicKeyInfo,
        )
        if sig_type == "EC-P384":
            return hashlib.sha384(der).digest()
        return hashlib.sha256(der).digest()
    if sig_type.startswith("RSA-"):
        der = pub.public_bytes(
            serialization.Encoding.DER,
            serialization.PublicFormat.PKCS1,
        )
        return hashlib.sha256(der).digest()
    raise SystemExit(f"不支持的签名类型: {sig_type}")


def c_byte_array(data: bytes, indent: str = "        ", macro: bool = False) -> str:
    parts = [f"0x{b:02x}" for b in data]
    lines = []
    for i in range(0, len(parts), 8):
        chunk = ", ".join(parts[i : i + 8]) + ","
        if macro:
            lines.append(indent + chunk + " \\")
        else:
            lines.append(indent + chunk)
    return "\n".join(lines)


def render_inc(hash0: bytes, hash1: bytes) -> str:
    return (
        "/* Auto-generated by scripts/sync_stm_otp_rotpk.py — do not edit by hand. */\n"
        "/* Included from otp_provision.c (STM flash-emulated OTP ROTPK). */\n"
        "    .bl2_rotpk_0 = {\n"
        f"{c_byte_array(hash0)}\n"
        "    },\n"
        "    .bl2_rotpk_1 = {\n"
        f"{c_byte_array(hash1)}\n"
        "    },\n"
        "    .bl2_nv_counter_0 = { INT64NULL },\n"
        "    .bl2_nv_counter_1 = { INT64NULL },\n"
        "    .bl2_nv_counter_2 = { INT64NULL },\n"
        "    .bl2_rotpk_2 = {\n"
        f"{c_byte_array(hash1)}\n"
        "    },\n"
    )


def write_if_changed(path: Path, content: str) -> bool:
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def kind_macro(name: str, data: bytes) -> str:
    return (
        f"#define {name} {{            \\\n"
        f"{c_byte_array(data, macro=True)}\n"
        "    }"
    )


def patch_provisioning_kind(path: Path, sig_type: str, hash0: bytes, hash1: bytes) -> bool:
    """Replace KIND_0/KIND_1 macros under the matching MCUBOOT_SIGN_* block."""
    text = path.read_text(encoding="utf-8")
    if sig_type == "EC-P256":
        gate = "elif defined(MCUBOOT_SIGN_EC256)"
        expect_len = 32
    elif sig_type == "EC-P384":
        gate = "elif defined(MCUBOOT_SIGN_EC384)"
        expect_len = 48
    elif sig_type == "RSA-2048":
        gate = "if (MCUBOOT_SIGN_RSA_LEN == 2048)"
        expect_len = 32
    elif sig_type == "RSA-3072":
        gate = "elif (MCUBOOT_SIGN_RSA_LEN == 3072)"
        expect_len = 32
    else:
        print(f"警告: provisioning.c 未同步（sig={sig_type}）", file=sys.stderr)
        return False

    if len(hash0) != expect_len or len(hash1) != expect_len:
        raise SystemExit(f"哈希长度不符: want {expect_len}, got {len(hash0)}/{len(hash1)}")

    pattern = re.compile(
        r"#define ASSEMBLY_AND_TEST_PROV_DATA_KIND_0\s*\{.*?\n\s*\}\n"
        r"#define ASSEMBLY_AND_TEST_PROV_DATA_KIND_1\s*\{.*?\n\s*\}",
        re.S,
    )

    idx = text.find(gate)
    if idx < 0:
        print(f"警告: provisioning.c 找不到 {gate}", file=sys.stderr)
        return False

    window_start = idx
    window_end = text.find("#else /* !MCUBOOT_BUILTIN_KEY */", window_start)
    if window_end < 0:
        window_end = text.find("#endif /* MCUBOOT_SIGN_RSA */", window_start)
    if window_end < 0:
        window_end = len(text)

    window = text[window_start:window_end]
    m = pattern.search(window)
    if not m:
        print("警告: provisioning.c 未找到 KIND_0/1 可替换块", file=sys.stderr)
        return False

    replacement = (
        kind_macro("ASSEMBLY_AND_TEST_PROV_DATA_KIND_0", hash0)
        + "\n"
        + kind_macro("ASSEMBLY_AND_TEST_PROV_DATA_KIND_1", hash1)
    )
    new_window = window[: m.start()] + replacement + window[m.end() :]
    new_text = text[:window_start] + new_window + text[window_end:]
    if new_text == text:
        return False
    path.write_text(new_text, encoding="utf-8")
    return True


def default_keys(tfm_root: Path, sig_type: str) -> tuple[Path, Path]:
    key_dir = tfm_root / "bl2" / "ext" / "mcuboot"
    mapping = {
        "EC-P256": ("root-EC-P256.pem", "root-EC-P256_1.pem"),
        "EC-P384": ("root-EC-P384.pem", "root-EC-P384_1.pem"),
        "RSA-2048": ("root-RSA-2048.pem", "root-RSA-2048_1.pem"),
        "RSA-3072": ("root-RSA-3072.pem", "root-RSA-3072_1.pem"),
    }
    if sig_type not in mapping:
        raise SystemExit(f"未知 MCUBOOT_SIGNATURE_TYPE: {sig_type}")
    a, b = mapping[sig_type]
    return key_dir / a, key_dir / b


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--tfm-root", type=Path, required=True)
    ap.add_argument("--sig-type", required=True, help="EC-P256 / EC-P384 / RSA-2048 / RSA-3072")
    ap.add_argument("--key-s", type=Path, default=None)
    ap.add_argument("--key-ns", type=Path, default=None)
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    tfm = args.tfm_root.resolve()
    sig = args.sig_type.strip()
    key_s = args.key_s or default_keys(tfm, sig)[0]
    key_ns = args.key_ns or default_keys(tfm, sig)[1]
    key_s = key_s.resolve()
    key_ns = key_ns.resolve()

    if not key_s.is_file():
        raise SystemExit(f"缺少 S 密钥: {key_s}")
    if not key_ns.is_file():
        raise SystemExit(f"缺少 NS 密钥: {key_ns}")

    k0 = load_private_key(key_s)
    k1 = load_private_key(key_ns)
    if sig.startswith("EC-P") and not isinstance(k0.public_key(), ec.EllipticCurvePublicKey):
        raise SystemExit(f"{key_s} 不是 EC 密钥，但 SIG={sig}")
    if sig.startswith("RSA-") and not isinstance(k0.public_key(), rsa.RSAPublicKey):
        raise SystemExit(f"{key_s} 不是 RSA 密钥，但 SIG={sig}")

    h0 = pubkey_hash_bytes(k0, sig)
    h1 = pubkey_hash_bytes(k1, sig)

    inc_path = (
        tfm
        / "platform"
        / "ext"
        / "target"
        / "stm"
        / "common"
        / "hal"
        / "provision"
        / "otp_rotpk_hashes.inc"
    )
    prov_path = tfm / "bl2" / "src" / "provisioning.c"

    changed = []
    if write_if_changed(inc_path, render_inc(h0, h1)):
        changed.append(str(inc_path.relative_to(tfm)))
        # Ensure ninja rebuilds otp_provision.c when only the .inc changes.
        otp_c = inc_path.with_name("otp_provision.c")
        if otp_c.is_file():
            otp_c.touch()
    if patch_provisioning_kind(prov_path, sig, h0, h1):
        changed.append(str(prov_path.relative_to(tfm)))

    if not args.quiet:
        print(f">>> OTP ROTPK sync  SIG={sig}")
        print(f"    S   {key_s.name}  sha={h0.hex()}")
        print(f"    NS  {key_ns.name}  sha={h1.hex()}")
        if changed:
            print("    已更新: " + ", ".join(changed))
        else:
            print("    已与当前密钥一致，无需修改")

    return 0


if __name__ == "__main__":
    sys.exit(main())
